//This represents each tile on the board.

const board = [
  { index: 1 },
  { index: 2 },
  { index: 3 },
  { index: 4 },
  { index: 5 },
  { index: 6 },
  { index: 7 },
  { index: 8 },
  { index: 9, type: 'color', value: 'red', name: 'heart' },
  { index: 10, type: 'color', value: 'orange', name: 'diamond' },
  { index: 11, type: 'color', value: 'yellow', name: 'star' },
  { index: 12, type: 'color', value: 'green', name: 'triangle' },
  { index: 13, type: 'color', value: 'blue', name: 'circle' },
  { index: 14, type: 'color', value: 'purple', name: 'square' },
  { index: 15, type: 'image', value: 'agustus', name: 'square' }, //IMAGE
  { index: 16, type: 'color', value: 'red', name: 'heart' },
  { index: 17 },
  { index: 18 },
  { index: 19 },
  { index: 20 },
  { index: 21 },
  { index: 22 },
  { index: 23 },
  { index: 24, type: 'color', value: 'orange', name: 'diamond' },
  { index: 25, type: 'color', value: 'yellow', name: 'star' },
  { index: 26, type: 'color', value: 'orange', name: 'diamond' },
  { index: 27, type: 'color', value: 'red', name: 'heart' },
  { index: 28, type: 'image', value: 'blueberry', name: 'square' },
  { index: 29, type: 'color', value: 'purple', name: 'square' },
  { index: 30, type: 'color', value: 'blue', name: 'circle' },
  { index: 31, type: 'color', value: 'green', name: 'triangle' },
  { index: 32, type: 'color', value: 'yellow', name: 'star' },
  { index: 33, type: 'color', value: 'green', name: 'triangle' },
  { index: 34 },
  { index: 35 },
  { index: 36 },
  { index: 37 },
  { index: 38 },
  { index: 39 },
  { index: 40 },
  { index: 41, type: 'color', value: 'blue', name: 'circle' },
  { index: 42, type: 'color', value: 'purple', name: 'square' },
  { index: 43, type: 'image', value: 'veruca', name: 'square' },
  { index: 44, type: 'color', value: 'red', name: 'heart' },
  { index: 45, type: 'color', value: 'orange', name: 'diamond' },
  { index: 46, type: 'color', value: 'yellow', name: 'star' },
  { index: 47, type: 'color', value: 'green', name: 'triangle' },
  { index: 48, type: 'color', value: 'blue', name: 'circle' },
  { index: 49 },
  { index: 50 },
  { index: 51 },
  { index: 52 },
  { index: 53 },
  { index: 54 },
  { index: 55 },
  { index: 56, type: 'color', value: 'purple', name: 'square' },
  { index: 57, type: 'image', value: 'Mike', name: 'square' }, //IMAGE
  { index: 58, type: 'color', value: 'purple', name: 'square' },
  { index: 59, type: 'color', value: 'blue', name: 'circle' },
  { index: 60, type: 'color', value: 'green', name: 'triangle' },
  { index: 61, type: 'color', value: 'yellow', name: 'star' },
  { index: 62, type: 'color', value: 'orange', name: 'diamond' },
  { index: 63, type: 'color', value: 'red', name: 'heart' },
  { index: 64, type: 'image', value: 'charlie', name: 'square' }, //IMAGE
  { index: 65, type: 'color', value: 'red', name: 'heart' },
  { index: 66 },
  { index: 67 },
  { index: 68 },
  { index: 69 },
  { index: 70 },
  { index: 71 },
  { index: 72 },
  { index: 73, type: 'color', value: 'orange', name: 'diamond' },
  { index: 74, type: 'color', value: 'yellow', name: 'star' },
  { index: 75, type: 'color', value: 'green', name: 'triangle' },
  { index: 76, type: 'color', value: 'blue', name: 'circle' },
  { index: 77, type: 'color', value: 'purple', name: 'square' },
  { index: 78, type: 'image', value: 'willy', name: 'square' }, //IMAGE
  { index: 79 },
  { index: 80 },
  { index: 81 },
  { index: 82 },
  { index: 83 },
  { index: 84 },
  { index: 85 },
  { index: 86 },
  { index: 87 },
  { index: 88 }
];

module.exports = board;
