//This represents each tile on the board.

const board = [
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  { index: 0, type: 'color', value: 'red', name: 'heart1' },
  { index: 1, type: 'color', value: 'orange', name: 'diamond1' },
  { index: 2, type: 'color', value: 'yellow', name: 'star1' },
  { index: 3, type: 'color', value: 'green', name: 'triangle1' },
  { index: 4, type: 'color', value: 'blue', name: 'circle1' },
  { index: 5, type: 'color', value: 'purple', name: 'square1' },
  { index: 6, type: 'image', value: 'agustus', name: 'agustus' }, //IMAGE
  { index: 7, type: 'color', value: 'red', name: 'heart2' },
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  { index: 8, type: 'color', value: 'orange', name: 'diamond2' },
  { index: 16, type: 'color', value: 'yellow', name: 'star2' },
  { index: 15, type: 'color', value: 'green', name: 'triangle2' },
  { index: 14, type: 'color', value: 'blue', name: 'cirlce2' },
  { index: 13, type: 'image', value: 'purple', name: 'square2' },
  { index: 12, type: 'color', value: 'blueberry', name: 'blueberry' }, //IMAGE
  { index: 11, type: 'color', value: 'red', name: 'heart3' },
  { index: 10, type: 'color', value: 'orange', name: 'diamond3' },
  { index: 9, type: 'color', value: 'yellow', name: 'star3' },
  { index: 17, type: 'color', value: 'green', name: 'triangle3' },
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  { index: 18, type: 'color', value: 'blue', name: 'circle3' },
  { index: 19, type: 'color', value: 'purple', name: 'square3' },
  { index: 20, type: 'image', value: 'veruca', name: 'veruca' },
  { index: 21, type: 'color', value: 'red', name: 'heart4' },
  { index: 22, type: 'color', value: 'orange', name: 'diamond4' },
  { index: 23, type: 'color', value: 'yellow', name: 'star4' },
  { index: 24, type: 'color', value: 'green', name: 'triangle4' },
  { index: 25, type: 'color', value: 'blue', name: 'circle4' },
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  { index: 26, type: 'color', value: 'purple', name: 'square4' },
  { index: 34, type: 'image', value: 'mike', name: 'mike' }, //IMAGE
  { index: 33, type: 'color', value: 'red', name: 'heart5' },
  { index: 32, type: 'color', value: 'orange', name: 'diamond5' },
  { index: 31, type: 'color', value: 'yellow', name: 'star5' },
  { index: 30, type: 'color', value: 'green', name: 'triangle5' },
  { index: 29, type: 'color', value: 'blue', name: 'circle5' },
  { index: 28, type: 'color', value: 'purple', name: 'square5' },
  { index: 27, type: 'image', value: 'charlie', name: 'charlie' }, //IMAGE
  { index: 35, type: 'color', value: 'red', name: 'heart6' },
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  { index: 36, type: 'color', value: 'orange', name: 'diamond6' },
  { index: 37, type: 'color', value: 'yellow', name: 'star6' },
  { index: 38, type: 'color', value: 'green', name: 'triangle6' },
  { index: 39, type: 'color', value: 'blue', name: 'circle6' },
  { index: 40, type: 'color', value: 'purple', name: 'square6' },
  { index: 41, type: 'image', value: 'willy', name: 'willy' }, //IMAGE
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {}
];

module.exports = board;
