//This represents each tile on the board.

const board = [
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  { index: 0, type: 'color', value: 'red', name: 'heart' },
  { index: 1, type: 'color', value: 'orange', name: 'diamond' },
  { index: 2, type: 'color', value: 'yellow', name: 'star' },
  { index: 3, type: 'color', value: 'green', name: 'triangle' },
  { index: 4, type: 'color', value: 'blue', name: 'circle' },
  { index: 5, type: 'color', value: 'purple', name: 'square' },
  { index: 6, type: 'image', value: 'Agustus', name: 'Agustus' }, //IMAGE
  { index: 7, type: 'color', value: 'red', name: 'heart' },
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  { index: 8, type: 'color', value: 'orange', name: 'diamond' },
  { index: 16, type: 'color', value: 'yellow', name: 'star' },
  { index: 15, type: 'color', value: 'orange', name: 'diamond' },
  { index: 14, type: 'color', value: 'red', name: 'heart' },
  { index: 13, type: 'image', value: 'Blueberry', name: 'Blueberry' },
  { index: 12, type: 'color', value: 'purple', name: 'square' },
  { index: 11, type: 'color', value: 'blue', name: 'circle' },
  { index: 10, type: 'color', value: 'green', name: 'triangle' },
  { index: 9, type: 'color', value: 'yellow', name: 'star' },
  { index: 17, type: 'color', value: 'green', name: 'triangle' },
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  { index: 18, type: 'color', value: 'blue', name: 'circle' },
  { index: 19, type: 'color', value: 'purple', name: 'square' },
  { index: 20, type: 'image', value: 'Veruca', name: 'Veruca' },
  { index: 21, type: 'color', value: 'red', name: 'heart' },
  { index: 22, type: 'color', value: 'orange', name: 'diamond' },
  { index: 23, type: 'color', value: 'yellow', name: 'star' },
  { index: 24, type: 'color', value: 'green', name: 'triangle' },
  { index: 25, type: 'color', value: 'blue', name: 'circle' },
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  { index: 26, type: 'color', value: 'purple', name: 'square' },
  { index: 34, type: 'image', value: 'MikeTV', name: 'MikeTV' }, //IMAGE
  { index: 33, type: 'color', value: 'purple', name: 'square' },
  { index: 32, type: 'color', value: 'blue', name: 'circle' },
  { index: 31, type: 'color', value: 'green', name: 'triangle' },
  { index: 30, type: 'color', value: 'yellow', name: 'star' },
  { index: 29, type: 'color', value: 'orange', name: 'diamond' },
  { index: 28, type: 'color', value: 'red', name: 'heart' },
  { index: 27, type: 'image', value: 'Charlie', name: 'Charlie' }, //IMAGE
  { index: 35, type: 'color', value: 'red', name: 'heart' },
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  { index: 36, type: 'color', value: 'orange', name: 'diamond' },
  { index: 37, type: 'color', value: 'yellow', name: 'star' },
  { index: 38, type: 'color', value: 'green', name: 'triangle' },
  { index: 39, type: 'color', value: 'blue', name: 'circle' },
  { index: 40, type: 'color', value: 'purple', name: 'square' },
  { index: 41, type: 'image', value: 'Willy', name: 'Willy' }, //IMAGE
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {}
];

module.exports = board;
